### ISSUE TITLE
Great software but more improvements

### ISSUE THREAD

**Issue by axisdos** [BeehiveForum/BeehiveForum#18]
Hey developer, I really like this piece of software. However, I think it needs more improvements such as:

1. SEO Features:
-SEO Friendly Url
-Canonical tag
-Noindex for subpages (page/2)
-Auto generate meta description using post excerpt

**Comment by HeyRatFans** [comment]
SEO Friendly Urls are not going to be easy to implement given the frameset nature of Beehive, at least not on the desktop browser version. The Mobile version might be doable, but would be a lot of work at this stage.

The other issues, canonical tag, auto-generate description etc., we already had - although I have refined them to comply with Google's documentation.
